[project]
name = "ml-risk-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "seaborn>=0.13.2",
    "streamlit>=1.45.0",
]
